name: pull request comment

on:
  pull_request_review_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload
        run: |
          echo "Event payload: ${{ toJson(github.event) }}"
