name: CI

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    name: Build & Lint
    if: contains(github.event.comment.body, 'run-actions')
    runs-on: ubuntu-latest

    steps:
      - name: Github API Request
          id: request
          uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
