name: CI

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    name: Build & Lint
    if: contains(github.event.comment.body, 'run-actions')
    runs-on: ubuntu-latest

    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
          ref: ${{fromJson(steps.request.outputs.data).head.ref}}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check for corresponding test file
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.tsx$'); do
            echo file
            test_file="${file%.tsx}.test.ts"
            if [ ! -f "$test_file" ]; then
              echo "Error: Corresponding test file '$test_file' is missing for file '$file'."
              exit 1
            fi
          done    
