name: CI

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Is Pull Request: ${{ github.event.issue.pull_request }}"
          echo "Event: ${{ toJson(github.event) }}"
      - name: Check if comment contains "CI-RUN"
        if: contains(github.event.comment.body, 'CI-RUN') && github.event.issue.pull_request
        run: |
          echo say hello
